#!/usr/bin/env bash
#
# Options
#
# --keep-git
# --no-mode
# --no-compile
# --no-static
# --no-db
# --no-composer
# --no-version-check

source "${PATH_DEPLOY}/router/verify-shared"

_do_title "Creating release in ${TSTAMP}"

[ -d "${PATH_RELEASE_NEW}" ] || mkdir "${PATH_RELEASE_NEW}"

cd "${PATH_RELEASE_NEW}"

# GIT
_do_title "Cloning Repository"
_do_titled_point " Repository:" "${REPO_URL}"
_do_line_break

if [ -z "${TSTAMP_DEBUG}" ]; then
    git clone --depth=1 "${REPO_URL}" . || _do_error "GIT"
else
    _do_point "Skipping as TSTAMP_DEBUG is set"
fi

if _flag_not_exists "--keep-git"; then
    _do_title "Removing GIT from release"
    rm -rf ./.git ./.gitignore
fi

# Shared Files
_do_title "Shared Files"

for SHARED_FILE in "${SHARED_FILES[@]}"; do
    SHARED_SOURCE_FILE="${PATH_SHARED}/${SHARED_FILE}"

    _do_point "${SHARED_SOURCE_FILE}"

    if [[ -d "${SHARED_SOURCE_FILE}" ]]; then
        SHARED_FILE_PARENT_DIR=`dirname "${SHARED_FILE}"`

        [ -d "${SHARED_FILE_PARENT_DIR}" ] || mkdir "${SHARED_FILE_PARENT_DIR}"
    fi

    ln -s ${PATH_SHARED}/${SHARED_FILE} ${SHARED_FILE}
done

# Composer
_do_title "Installing dependencies via Composer"

if [ -z "${TSTAMP_DEBUG}" ]; then
    if _flag_exists "--no-composer"; then
        _do_skip_flag
    else
        composer install --no-dev || _do_error "Composer"
    fi
else
    _do_point "Skipping as TSTAMP_DEBUG is set"
fi

# Magento Version Check
_do_title "Magento Version"

if _flag_exists "--no-version-check"; then
    _do_skip_flag
else
    bin_magento "" || _do_error "Bin/Magento"
    _do_line_break
    bin_magento --version || _do_error "Version"
    _do_line_break
fi

# Mage Mode
_do_title "Magento Mode"

if _flag_exists "--no-mode"; then
    _do_skip_flag
else
    _do_point "MAGE_MODE=${MAGE_MODE}"
    _do_line_break
    bin_magento deploy:mode:set --skip-compilation "${MAGE_MODE}" || _do_error "MAGE_MODE"
fi

# Compile
_do_title "Compiling Magento"

if _flag_exists "--no-compile"; then
    _do_skip_flag
else
    _do_line_break
    bin_magento setup:di:compile || _do_error "Compile"
fi

# Static Assets
_do_title "Compiling Static Assets"

if _flag_exists "--no-static" || [ "${IS_DEV_MODE}" = 1 ]; then
    _do_skip_flag
else
    _deploy_static_assets || _do_error "Static Content"
fi

# Upgrade DB
_do_title "Upgrading the Database"

if _flag_exists "--no-db"; then
    _do_skip_flag
else
    _do_point "First enabling maintenance mode on the live site"

    if [ -d "${PATH_RELEASE_NEW}" ]; then
        (cd "${PATH_CURRENT}" && (bin_magento maintenance:enable) && cd -) \
            || _do_error "Maintenance on live"
    else
        _do_point "Skipping as live site does not exist"
    fi

    _do_point "Now upgrading the database"
    _do_line_break

    bin_magento setup:upgrade --keep-generated || _do_error "Upgrade DB. Live site may be down now due to maintenance mode."
fi

cd "${PATH_BASE}"

# Symlink
_do_title "Current Symlink"

CURRENT_RESOLVED=$(readlink "${PATH_CURRENT}")

_do_point "PATH_CURRENT=${PATH_CURRENT}"
_do_point "Current=${CURRENT_RESOLVED}"
_do_point "New Current=releases/${TSTAMP}"

[ -L "${PATH_CURRENT}" ] && rm "${PATH_CURRENT}"

ln -s "releases/${TSTAMP}" current

_do_title "Verify"

NEW_CURRENT_RESOLVED=$(readlink "${PATH_CURRENT}")

_do_point "NewCurrentResolved=${NEW_CURRENT_RESOLVED}"

source "${PATH_DEPLOY}/router/reload"
