#!/usr/bin/env bash

function _source_file {
    if [ -f "${1}" ]; then
        source "${1}"
        return 1;
    fi

    _do_error "File does not exist: ${1}"
    exit 1
}

function _assert_config {
    if [ -z "${1}" ]; then
        _do_error "${2} is not set or is empty in the config"
        exit 1
    fi
}

_source_file "${PATH_DEPLOY}/inc/output"

if [ -z "${TSTAMP_DEBUG}" ]; then
    TSTAMP=`date +%s`
else
    TSTAMP="${TSTAMP_DEBUG}"
fi

PATH_SHARED="${PATH_BASE}/shared"
PATH_CURRENT="${PATH_BASE}/current"
PATH_RELEASES="${PATH_BASE}/releases"
PATH_RELEASE_NEW="${PATH_RELEASES}/${TSTAMP}"

CURRENT_RELEASE="$(basename "$(readlink ${PATH_CURRENT})")"

_source_file "${PATH_DEPLOY}/inc/default-config"
_source_file "${PATH_BASE}/.deploy-config"

_assert_config "${PROJECT_ID}" "PROJECT_ID"
_assert_config "${REPO_URL}" "REPO_URL"
_assert_config "${SHARED_FILES_LIST}" "SHARED_FILES_LIST"
_assert_config "${MAGE_MODE}" "MAGE_MODE"

if ! declare -F _do_php_reload >/dev/null; then
    _do_error "_do_php_reload function is not defined in .deploy-config"
    exit 1
fi

function bin_magento {
    php -dmemory_limit="${PHP_MEMORY_LIMIT}" bin/magento "$@"
}

# Setup flags
FLAGS=()
for i in "$@" ; do
    FLAGS+=("${i}")
done

function _flag_exists {
    local FLAG="${1}"
    for arg in "${FLAGS[@]}"; do
        [[ "$arg" == "$FLAG" ]] && return 0
    done
    return 1
}

function _flag_not_exists {
    _flag_exists "${1}" && return 1;
    return 0;
}

if _flag_exists "--dry-run"; then
    IS_DRY_RUN=1
else
    IS_DRY_RUN=0
fi

# Load shared files into array
SHARED_FILES=()
while IFS= read -r SHARED_FILE; do
    SHARED_FILES+=("${SHARED_FILE}")
done <<< "$SHARED_FILES_LIST"

# Mage Mode
_flag_exists "--dev" && MAGE_MODE="developer"
[ "${MAGE_MODE}" == "developer" ] && IS_DEV_MODE=1 || IS_DEV_MODE=0

cd "${PATH_BASE}"

# Create base dirs
[ -d "${PATH_RELEASES}" ] || mkdir "${PATH_RELEASES}"
[ -d "${PATH_SHARED}" ]   || mkdir "${PATH_SHARED}"

if [ ! -z "${MAGE_DEPLOY_THEME_LIST}" ]; then
    DEPLOYED_THEMES=()
    while IFS= read -r theme; do
        DEPLOYED_THEMES+=("$theme")
    done <<< "$MAGE_DEPLOY_THEME_LIST"
fi

function _deploy_static_assets {
    if [ ! -z "${DEPLOYED_THEMES}" ]; then
        for THEME in "${DEPLOYED_THEMES[@]}"; do
            _do_line_break
            bin_magento setup:static-content:deploy -f "${MAGE_DEPLOY_STATIC_ASSETS_LOCALE}" --theme "${THEME}" --no-parent || return 1
        done
    else
        _do_point "No themes specified so deploying all themes"
        _do_line_break
        bin_magento setup:static-content:deploy -f "${MAGE_DEPLOY_STATIC_ASSETS_LOCALE}" || return 1
    fi

    _do_line_break

    return 0
}