#!/usr/bin/env bash

COLOR_RED='\033[0;31m'
COLOR_YELLOW='\033[1;33m'
COLOR_STOP='\033[0m'

function color_yellow {
    echo -e "${COLOR_YELLOW}${1}${COLOR_STOP}"
}

function color_red {
    echo -e "${COLOR_RED}${1}${COLOR_STOP}"
}

function _do_title {
    BAR="--------------------------------------------------------";
    echo ""
    echo "${BAR}"
    echo "** ${1} **"
    echo "${BAR}"
}

function _do_error {
    BAR="_________________________________";
    echo ""
    echo ""
    echo -e "${COLOR_RED}** ERROR ** ${COLOR_STOP}"
    echo ""
    echo "   ${1}"
    echo ""
    pwd
    echo ""
    exit 1
}

function _do_point {
    echo "- ${1}"
}

function _do_titled_point {
    echo -e "  \033[2m${1}${COLOR_STOP} \033[1m${2}${COLOR_STOP}"
}

function _do_skip_flag {
    echo -n "   "
    color_yellow "Skipping this step as user requested to do so via flag"
}

function _do_line_break {
    echo ""
}